language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

services: mongodb

gemfile:
  - Gemfile
  - Gemfile.rails4

env:
  - "SORCERY_ORM=active_record"
  - "SORCERY_ORM=mongoid"
  - "SORCERY_ORM=mongo_mapper"
  - "SORCERY_ORM=datamapper"

before_script:
  - mysql -e 'create database sorcery_test;'

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile.rails4
      env: "SORCERY_ORM=datamapper"

    - rvm: 2.0.0
      gemfile: Gemfile.rails4
      env: "SORCERY_ORM=datamapper"

    - rvm: 2.1.0
      gemfile: Gemfile.rails4
      env: "SORCERY_ORM=datamapper"
